# Generated by Django 5.2.4 on 2025-08-14 12:02

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("website", "0002_rename_parent_folder_folder_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={},
        ),
        migrations.RemoveField(
            model_name="document",
            name="name",
        ),
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together={("name", "property", "parent")},
        ),
        migrations.AddField(
            model_name="property",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="county",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="number_of_units",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="property",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="purchase_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="city",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="record",
            name="county",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="custom_user_set",
                related_query_name="custom_user",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="custom_user_permissions_set",
                related_query_name="custom_user",
                to="auth.permission",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="property_documents/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(help_text="Street address", max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="postcode",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("HMO", "HMO (House in Multiple Occupation)"),
                    ("Residential", "Residential"),
                    ("Commercial", "Commercial"),
                    ("Storage", "Storage"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="record",
            name="current_residence",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="record",
            name="email",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="record",
            name="move_in_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="record",
            name="next_of_kin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="occupancy_status",
            field=models.CharField(
                choices=[
                    ("Vacant", "Vacant"),
                    ("Occupied", "Occupied"),
                    ("Previous", "Previous"),
                ],
                default="Vacant",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="record",
            name="postcode",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="tenantimage",
            name="image",
            field=models.ImageField(upload_to="tenant_images/%Y/%m/%d/"),
        ),
        migrations.RemoveField(
            model_name="folder",
            name="created_at",
        ),
    ]
