# Generated by Django 5.2.4 on 2025-08-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_property_options_remove_document_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("one_bedroom", "1 Bedroom"),
                    ("two_bedroom", "2 Bedroom"),
                    ("three_bedroom", "3 Bedroom"),
                    ("studio", "Studio"),
                    ("flat", "Flat"),
                    ("house", "House"),
                    ("block", "Block"),
                ],
                max_length=50,
            ),
        ),
    ]
