# Generated by Django 5.2.4 on 2025-08-18 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_property_property_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=50, unique=True)),
                ("date_issue_reported", models.DateField()),
                ("description_of_issue", models.TextField()),
                (
                    "job_allocated",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Contractor 1", "Contractor 1"),
                            ("Contractor 2", "Contractor 2"),
                            ("Contractor 3", "Contractor 3"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_completed", models.DateField(blank=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="website.property",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="website.record",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="task_images/")),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("pre-inspection", "Pre-Inspection"),
                            ("dominic", "Dominic"),
                            ("confirmation", "Confirmation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="website.task",
                    ),
                ),
            ],
        ),
    ]
