# Generated by Django 5.2.4 on 2025-08-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_task_taskimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="job_allocated",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Waleed", "Waleed"),
                    ("Nadeem", "Nadeem"),
                    ("Ruth", "Ruth"),
                    ("Sheraz", "Sheraz"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
