# Generated by Django 5.2.4 on 2025-08-19 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_task_job_allocated"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantPropertyRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("move_in_date", models.DateField()),
                ("move_out_date", models.DateField(blank=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_relationships",
                        to="website.property",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_relationships",
                        to="website.record",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "property", "move_in_date")},
            },
        ),
    ]
